### ISSUE TITLE
Application permissions

### ISSUE THREAD

**Issue by AustinBrunkhorst** [microsoft/bookings-samples#10]
I'm building a homepage that is essentially a reskin of the hosted bookings page. #7 references application permissions for unattended access, but It wasn't clear how @jcfetzer was able to work around this.

Without application permissions, I don't see any way that I can replicate the hosted page's experience, as an administrator of the bookings business needs to be logged in. 

Is it possible to create a long-lived access token or certificate or something for a web service?

**Comment by hrajur** [comment]
@AustinBrunkhorst have you solved this somehow ? 
I wanted also to make custom page and add some functionality - like avoid duplicate reservations by the same person.

**Comment by AustinBrunkhorst** [comment]
> @AustinBrunkhorst have you solved this somehow ? 

I haven't solved this unfortunately. I ended up not using Bookings for this project.
