### ISSUE TITLE
Event's on 0365 calendar affect availability not working via api

### ISSUE THREAD

**Issue by GavinThomas1192** [Microsoft/bookings-samples#12]
Hello. 

I am implementing the bookings app through the api. When calling all staff members schedules. 
https://graph.microsoft.com/beta/bookingBusinesses/xxx@xxx.com/staffMembers

I receive only the schedules of staff members that have been manually inputted into the bookings ui under 'staff'. Meaning if you scheduled a staff for working 0800-1700 that staff is available the entire time. The staff's personal 365 calendar isn't affecting availability. The Event's on 0365 calendar affect availability box is checked true.

The response doesn't relate to the staff's calendar at all. 
If I go to the Bookings ui page. That is created from the bookings app. It accurately removes timeslots not available based on the staff's 365 calendar.

**Comment by fpintos** [comment]
Hi Gavin, as it stands today the /staffMembers call simply returns the list of staff members; as part of the properties it will contain their working hours, but it does not provide the availability for that staff member.
In other words, the current version of the API is oriented to setting up the list of staff members.
As you noticed, the published page goes thru the extra step of querying the member's calendar; however that functionality is not available in the graph API today.
