### ISSUE TITLE
Get available dates for staff members

### ISSUE THREAD

**Issue by moisesynfam** [microsoft/bookings-samples#13]
Is there a way of getting the available dates for staff members the same way the published Scheduling Page  does?  I know the the dates are pulled sending the staff members IDs to this endpoint:
https://outlook.office365.com/owa/calendar/xxxx@xxxx.com/bookings/service.svc/GetStaffBookability
But these staff members IDs required to be sent are different from the ones retrieved from the Bookings API.

**Comment by fpintos** [comment]
Hi Moises,

It will indeed be nice to have this functionality built into the API; right now it is not there.

If you want to call the underlying GetStaffBookability you can map the IDs by converting the GUID to a base64 string:

id_in_getStaffBookability = Convert.ToBase64String(new Guid(id_from_Graph).ToByteArray())

**Comment by fpintos** [comment]
(leaving this open so people can see it easily)

**Comment by arielpedraza** [comment]
Could you provide a sample of how you are hitting that endpoint and the expected payload?

**Comment by Tronald** [comment]
An example of using this would be awesome. I can't seem to find any documentation for this.

**Comment by n8its** [comment]
What's the status on an example on this? i was gonna make some custom codes, but if there is something built already it would be helpful.

**Comment by rahuldayal** [comment]
how to pass staff id. i am seeing staff id is encoded but don't know how it is encoded.

**Comment by mrdj07** [comment]
Hi y'all, here's a working example in PHP in Laravel:

`
function getStaffBookability(string $calendar, string $month, string $staffUuid, string $serviceId) {
        $start = (new Carbon("{$month}-01"));
        $end = $start->copy()->endOfMonth();
        $staffId = \Abublihi\Guid\ToBase64::encode($staffUuid);
        $serviceId = str_replace('==', '2', \Abublihi\Guid\ToBase64::encode($serviceId));
        $payload = [
            'StaffList' => [
                $staffId,
            ],
            'Start' => $start->format('Y-m-d').'T00:00:00',
            'End' => $end->format('Y-m-d').'T00:00:00',
            'ServiceId' => $serviceId,
        ];

        return Http::post("https://outlook.office365.com/owa/calendar/{$calendar}/bookings/service.svc/GetStaffBookability", $payload)->json();`
