### ISSUE TITLE
Bookings customer phone breaking change

### ISSUE THREAD

**Issue by jcfetzer** [microsoft/bookings-samples#14]
Hi, it appears that a change has occurred in the graph api for the bookings customer phone.  For the past year the following returned a valid phone number.

id eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerPhone')

I am now seeing the result returned with "undefined" preceding the phone number.  I believe this is due to the country code being added in the Bookings UI.  Now I see this returned (see the value):

                {
                    "id": "String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerPhone",
                    "value": "undefined3146318700"
                }

Can you please advise on how to properly request/process the phone number now?

Thanks,
Jerry

_Originally posted by @jcfetzer in https://github.com/Microsoft/bookings-samples/issues/7#issuecomment-478770092_

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
