### ISSUE TITLE
How can One Get the Self Service Page Link 

### ISSUE THREAD

**Issue by Tronald** [microsoft/bookings-samples#17]
I see the`selfServiceId` return from the Bookings API, but the self service page link id is different. Is there a way to extract the self service page link ID from either the bookings API or event API using `singleValueExtendedProperties`.

This would be extremely useful, as customers may lose this or the company may wish to rebook on their behalf. If we could extract this ID we reference direct links to this page.

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
