### ISSUE TITLE
authorization

### ISSUE THREAD

**Issue by n8its** [microsoft/bookings-samples#18]
So i created the app on azure, and place the ID in the program, i then use the localhost as the Uri, but i keep getting this error after I enter the uri in the console. I also turn some other feature on azure client type on. What it my missing in the error?

System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

**Comment by Tronald** [comment]
Have you created a client secret ID to pass in Azure yet? Judging by the error, it's expecting a client secret ID. You can create this in the Certificates and secrets section.

![image](https://user-images.githubusercontent.com/24424871/93632714-a49d1e80-f9a2-11ea-8e69-e4025f1f3c0f.png)

**Comment by n8its** [comment]
I did, do I need to put that code some where in the app also?

![image](https://user-images.githubusercontent.com/51927991/93634579-74f81180-f9b6-11ea-818f-2d5b3c8bfd17.png)

**Comment by Tronald** [comment]
It depends on how you are authenticating. For web and desktop apps you shouldn't need it as the user authenticates with their account. If it's a daemon app then you would need it. Are using the documentation provided in the "Quickstart" menu located at the top to build your authentication? Do you have a code sample of where it's failing?

**Comment by n8its** [comment]
I am using your own codes, just added the clientID and created the app on azure.

**Comment by n8its** [comment]
this is the error that it gives me once I click the login user.

System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

the code that calls for login is below
   var authenticationResult = authenticationContext.AcquireTokenAsync(
                    GraphService.ResourceId,
                    clientApplicationAppId,
                    clientApplicationRedirectUri,
                    new PlatformParameters(PromptBehavior.RefreshSession)).Result;

thats where it fails.

**Comment by n8its** [comment]
nvm, I was able to figure it out. Thanks
