### ISSUE TITLE
_ServiceNotes Empty

### ISSUE THREAD

**Issue by n8its** [microsoft/bookings-samples#19]
I was wondering why serviceNotes comes back empty when there is data on bookings.

![image](https://user-images.githubusercontent.com/51927991/94042948-cb3bca80-fd91-11ea-87cb-de0796eb1a88.png)

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
