### ISSUE TITLE
Adding a Group Bookings Service at the Calendar Level

### ISSUE THREAD

**Issue by mcmpistachio** [microsoft/bookings-samples#21]
I'm trying to build a training schedule for our business services company. We have the Services (course) built out and are able to only use the group scheduling one way. Each course has to be given a 'Not Bookable' as a general distinction then the individual dates and times for the allowed class time has to be entered as an additional time.

We have been able to add classes under the Calendar view which is preferable but the class is not able to add attendees from the client side.
![Screenshot 2020-10-26 154152](https://user-images.githubusercontent.com/49801826/97232135-3f5afb00-17a2-11eb-862a-dd1f86b10840.png)

Is there a workaround for situations like this that could also make it a bit easier to manage?

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
