### ISSUE TITLE
MS Booking internal API giving 401 Unauthorized

### ISSUE THREAD

**Issue by rahuldayal** [microsoft/bookings-samples#22]
MS Booking Internal API https://outlook.office.com/owa/service.svc?action=GetBookingCalendarPublishing&app=Bookings&n=10 giving me 401 unauthorised error while calling from Postman. Can anyone help me to find out how to call this API from postman or any other way.

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
