### ISSUE TITLE
Get availability dates which is published from publishing page

### ISSUE THREAD

**Issue by rahuldayal** [microsoft/bookings-samples#23]
Hello All,
how to get available date from publishing page.  Below image will give you good idea what i am talking about.
![image](https://user-images.githubusercontent.com/8329420/115268940-6e05cd00-a158-11eb-8a49-2ae1915f1d38.png)

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
