### ISSUE TITLE
Create a group appointment

### ISSUE THREAD

**Issue by BhagiLimbu** [microsoft/bookings-samples#26]
Hi There,

I am looking at options to create a group appointment via API. I want 3 people of family members who can input one profile on the website reserve (bookings) for 3 people. The recently released added two properties on booking appointment API "maximumAttendeesCount" and "filledAttendeesCount". If I set 3 instead of 1 on filledAttendeesCount, but provide only one customer profile information. Can MS Bookings count 3 appointments instead of 1? 

Any suggestion?

With Much Metta!

**Comment by fpintos** [comment]
I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
