### ISSUE TITLE
Native Azure AD application registration fails

### ISSUE THREAD

**Issue by robertas-jurkaitis** [Microsoft/bookings-samples#6]
Hello,

One of the steps for setting this thing up doesn't work for me. Am I doing anything wrong here?

```
Edit the application manifest in Azure, and include this under requiredResourceAccess, so the application will require access to the Bookings API*:
{
    "resourceAppId": "a6f98bd3-1059-4225-8f94-fce712c45742",
    "resourceAccess": [{ "id": "994019ca-1a02-4fd8-9fd6-987c7c09c426", "type": "Scope" }]
}
```

This results in a screenshot below:
![screenshot_1](https://user-images.githubusercontent.com/25228044/37397087-607d42aa-2783-11e8-9fe7-e296848e2707.png)

And, ultimately, InitializeTenant.ps1 fails because of the below:
```
AADSTS65005: The app needs access to a service ("https://microsoft.onmicrosoft.com/bookingsodataapi") that your organization "e354aff0-3c35-435d-b168-ac0bf6b5fc3b" has not subscribed to or enabled. Contact your IT Admin to review the configuration of your service subscriptions.
```

**Comment by fpintos** [comment]
I usually initialize the tenant before registering the application and that seems to work consistently.
