### ISSUE TITLE
Daemon process with Bookings API

### ISSUE THREAD

**Issue by jcfetzer** [Microsoft/bookings-samples#7]
Hi, I’m able to get the sample code to work and Postman requests when authenticating with the Native app registration and using the Auth Code flow (where I’m prompted to login to AAD before getting a token).  All is good.

However, I’m trying to setup a daemon (no user interaction or login) process to retrieve bookings appointments nightly.  I’ve added an app registration of type Web app / API and authenticating by retrieving the token with the Client Credentials flow.  I can get a token, but when making the Bookings API Appointments request with the token, I receive a 401 unauthorized.  I see that there are no Application Permissions for the Bookings OData API in Azure, only Delegated Permissions.  Is what I’m trying to do possible with the current Bookings API and related permissions?  Is seems it will only work when logging in as a user and the delegated permissions are honored.

I have also tried making a Graph API request for Events (per the Webhooks question here).  I can retrieve some Event data but the subject, bodyPreview and body values appear to strip out Customer data (see below).  And the Events do not list Customer data that was entered for the Bookings appointment, only the Staff data is listed under the Attendees key.  Are there any other Graph API categories that might provide this customer information?  I’ve checked with the Graph Explorer and haven’t been able to find the customer data.  

Interestingly, when using the Graph Explorer while logged in with my user account, the subject,  bodyPreview and body of the Event response ARE populated with the Customer data.  If I can retrieve this from a request made in code with Client Credentials, I could parse out the Customer info and be good to go.  But as noted above, the Customer data gets stripped out.  Any ideas on this?

Per Postman call using Client Credentials token:
 
![image](https://user-images.githubusercontent.com/11180393/40700956-cad80498-6390-11e8-847c-e56900656fd6.png)

Per Graph Explorer call (logged in with my user credentials):
 
![image](https://user-images.githubusercontent.com/11180393/40700959-d1ea8f12-6390-11e8-806c-2cdab3549275.png)

Thank you,
Jerry

**Comment by fpintos** [comment]
Hi Jerry, you are correct that this API currently does not support application permissions.

Reading the events themselves is an option, however some of the information you are looking for would be available only as [extended properties](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/extended-properties-overview).

For example, this should help you get the name, email and phone of the customer from the corresponding calendar event that holds the data of a booking appointment:
```
https://graph.microsoft.com/beta/users/{businessId}/events?$expand=singleValueExtendedProperties($filter=id eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerEmail' or id eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerName' or id eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerPhone')
```

If necessary, we can track down the names of the other properties.

That being said, I've never tried this from a daemon process; let me know if it works.

**Comment by jcfetzer** [comment]
Hi Fabio, thanks so much for the quick response and useful information.  This looks very promising and I'm getting the data needed with my initial test in Postman with client credentials token.  I'll report back with the full results.

**Comment by jcfetzer** [comment]
Hi Fabio,
Just a follow up on my previous questions...in particular I'd really like to be able to get the Address data from the bookings event.  Any pointers on how I can identify the address field(s) like the others:

singleValueExtendedProperties($filter=id eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerEmail'

Thanks,
Jerry

**Comment by fpintos** [comment]
Addresses are not that simple...individual pieces of an address are stored into separate properties.
Let me see if I can find out their names...

**Comment by fpintos** [comment]
Notes, if I'm not mistaken, are in the Body of the calendar event.

As for filtering by date, you should be able to do it with this syntax - note there are no quotes around the date value:
```
... /events?$filter=createdDateTime gt 2017-09-28Z
```

**Comment by jcfetzer** [comment]
Thank you!  Exactly what I needed.

**Comment by jcfetzer** [comment]
Hi Fabio,
One follow up question...is it possible to retrieve data for custom Bookings fields?  I've added a new dropdown via the Bookings admin UI and would like to retrieve the data via my Graph call.  Is there a way I can determine the property name and guid to use in the request?  Any documentation on this that I might reference?

Thanks again.

**Comment by fpintos** [comment]
It looks like we have these answers stored in this extended property:
Binary {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemAnsweredCustomQuestions

From what I can see, it is a base64-encoded JSON string, and in there you'll find the data.

I'll ask the product team about plans to publish the underlying schema; until it is documented, there's always a small chance that it can change, so take this info with some caution.

**Comment by jcfetzer** [comment]
Thank you.  This works great!

**Comment by fpintos** [comment]
I'm glad I could help. Feel free to reopen this is you have more questions.

**Comment by jcfetzer** [comment]
Hi, it appears that a change has occurred in the graph api for the bookings customer phone.  For the past year the following returned a valid phone number.

id eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerPhone')

I am now seeing the result returned with "undefined" preceding the phone number.  I believe this is due to the country code being added in the Bookings UI.  Now I see this returned (see the value):

                {
                    "id": "String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemCustomerPhone",
                    "value": "undefined3146318781"
                }

Can you please advise on how to properly request/process the phone number now?

Thanks,
Jerry

**Comment by Tronald** [comment]
I am attempting the extended property for "custom booking questions" as described above using the the provided ID and NAME like so.

```
https://graph.microsoft.com/beta/users/{businessid}/events?$expand=singleValueExtendedProperties($filter%3Did eq 'String {ccb88e73-951a-4b10-bb49-e6628b8d8494} Name BookingItemAnsweredCustomQuestions')
```

It's saying "The extended property attribute combination is invalid.". The graph api call works using "BookingItemCustomerPhone" though.

Did the ID or NAME change for "BookingItemCustomerPhone"?

**Comment by englertibor** [comment]
Hi @fpintos,
we are trying to work with Booking data the same way as @jcfetzer, thus using a daemon process without user interaction. All the extended properties you mentioned are working just fine, except for the case where are multiple customers booked for the same meeting. Would you care to share the names of the extended properties to access information such as the name, phone and e-mail of the multiple customers for the same booked event?

Thank you in advance.
Tibor

**Comment by brad302** [comment]
@fpintos are you able to provide a list of all custom fields that have been added to the calendar event?  Would be nice to know what else we can get our hands on.  Is there a way I can see that list of configured fields myself in my own tenant?!?

Thanks

Brad

**Comment by fpintos** [comment]
@jcfetzer @englertibor @brad302 I haven't been working on the Bookings API for a while now, so I'm afraid I don't have the answers you're looking for here. The API for extended properties is documented [here](https://learn.microsoft.com/en-us/graph/api/resources/extended-properties-overview?view=graph-rest-1.0), but I'm afraid I don't have a list of properties. Keep in mind that using extended properties is akin to using implementation details, so changes to the service can break any use of those properties without notice. It might be best to contact support, see if they have an approved list of properties you can use, and if there is any roadmap/timeline to include anything missing in the official schema.
