### ISSUE TITLE
Services are sorted by create date

### ISSUE THREAD

**Issue by Chotimir** [Microsoft/bookings-samples#8]
Hello,

Today I discovered that services are sorted by create date:
![image](https://user-images.githubusercontent.com/877387/41846384-cb580b66-7876-11e8-8006-bdd3919b029f.png)
The same on a booking page. Should it be that way? I think sorting by name is more intuitive.

(Sorry if I posted it in a wrong issue tracker)

Greetings

**Comment by fpintos** [comment]
Thanks @Chotimir , from an API perspective, you can ask the results to be sorted by a particular property.
For example:
```
GET https://graph.microsoft.com/beta/bookingBusinesses/{businessId}/services?$orderby=displayName
```

For the UI itself, use the feedback channel to vote on this idea:
https://outlook.uservoice.com/forums/314907-microsoft-bookings/suggestions/16782892-more-sorting-options-for-services
